id: P008181
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG25027
  title: བཤད་པའི་རྒྱུད།
  author: ''
  volumes:
    5153b59bbf09474eb9f9a45b1d2259d6:
      image_group_id: I1KG25029
      title: ''
      volume_number: 1
      total_pages: 194
      base_file: v001.txt
